name: .NET CI/CD with Docker Deployment

on:
    workflow_run:
        workflows:
            - .NET CI/CD Build and Upload Artifacts
        types:
            - completed

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: published-files
                  path: ./publish

            - name: Build Docker image
              run: docker build -t apevolo-api:latest -f Ape.Volo.Api/Dockerfile .

            - name: Add SSH key
              uses: webfactory/ssh-agent@v0.9.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add server to known_hosts
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
                  chmod 600 ~/.ssh/known_hosts

            - name: Deploy to server
              run: |
                  docker save apevolo-api:latest | ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker load"
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker stop apevolo-api || true && docker rm apevolo-api || true"
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker run -d -p 80:8002 --name apevolo-api apevolo-api:latest"
